spring.application.name=aipowered

# Database Connection
spring.datasource.url=jdbc:mysql://mysql:3306/employee_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# This helps you see the actual values in the SQL logs
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
ai.api.key=${OPENAI_API_KEY}